### ISSUE TITLE
授業を寝ないで真面目に受けるには

### ISSUE THREAD

**Issue by NaoKi0314** [wapli/Practice#12]
今日も寝てる時に、当てられて公開処刑をくらいました。

**Comment by anon622** [comment]
まじかよ、わらうｗ
なんで寝たんですか？

**Comment by NaoKi0314** [comment]
授業がつまらなかったからです

**Comment by NakanishiKenta** [comment]
手を動かしていたら眠気は飛ぶはず～

**Comment by NakanishiKenta** [comment]
確かに眠たい授業はある

**Comment by NaoKi0314** [comment]
手を動かしているはずの数学でも余裕で寝てます。

**Comment by anon622** [comment]
一番後ろの席に座るから授業が頭に入ってこないんだと思います
たぎくんの横の席に座るのはどうでしょうか？
そうしたら万が一寝てしまった時も起こしてもらえると思います

**Comment by anon622** [comment]
私はピンチの時に目薬を差します
しみるタイプの目薬を購入するのはどうでしょうか？

**Comment by NakanishiKenta** [comment]
僕がこの方法で眠気が飛ぶのはたぶん二度寝してるからでしょう

**Comment by NakanishiKenta** [comment]
まいてぃあ～し～える～

**Comment by anon622** [comment]
暑くなると頭が回らないと思います
服を脱ぐか水分を取るといいでしょう
また、私は`やばいときには濡れタオルを用意してます`

**Comment by NaoKi0314** [comment]
> 一番後ろの席に座るから授業が頭に入ってこないんだと思います
> たぎくんの横の席に座るのはどうでしょうか？
> そうしたら万が一寝てしまった時も起こしてもらえると思います

そんなことをしたら携帯がいじれません

**Comment by NaoKi0314** [comment]
> 私はピンチの時に目薬を差します
> しみるタイプの目薬を購入するのはどうでしょうか？

目薬がさせません

**Comment by anon622** [comment]
> 一番後ろの席に座るから授業が頭に入ってこないんだと思います
> たぎくんの横の席に座るのはどうでしょうか？
> そうしたら万が一寝てしまった時も起こしてもらえると思います
> 
> そんなことをしたら携帯がいじれません

いや、講義中に携帯を触らないでください笑

**Comment by NakanishiKenta** [comment]
> 一番後ろの席に座るから授業が頭に入ってこないんだと思います
> たぎくんの横の席に座るのはどうでしょうか？
> そうしたら万が一寝てしまった時も起こしてもらえると思います
> 
> そんなことをしたら携帯がいじれません

ケータイいじりたい衝動はもはや性格なのであきらめましょう

**Comment by NaoKi0314** [comment]
> 暑くなると頭が回らないと思います
> 服を脱ぐか水分を取るといいでしょう
> また、私は`やばいときには濡れタオルを用意してます`

これ以上脱いでしまうと全裸になってしまいます。
濡れタオルは心地よくて快眠できそうですね。今度実践してみます。

**Comment by NaoKi0314** [comment]
やっぱり寝ます
