### ISSUE TITLE
デブ化を止めるためには

### ISSUE THREAD

**Issue by anon622** [wapli/Practice#7]

**Comment by anon622** [comment]
最近愛音のデブ化が止まりません。どうしたらいいでしょうか？

**Comment by risako1110** [comment]
食生活を改める

**Comment by risako1110** [comment]
坂を上りましょう

**Comment by anon622** [comment]
最近学食のご飯の量をSからSSに変えてみました

**Comment by risako1110** [comment]
お菓子を食べるのを控えるとか???

**Comment by risako1110** [comment]
よく噛んでたべよう

**Comment by risako1110** [comment]
一口３０回噛みましょう

**Comment by anon622** [comment]
よく噛むように心がけます
お菓子は勝手に手が伸びてしまいます
気づいたら食べてしまいます

**Comment by risako1110** [comment]
それは大変だあ

**Comment by anon622** [comment]
**海に行くという予定を立てるのはどうでしょうか？**

**Comment by risako1110** [comment]
**一回気持ち悪くなるまで食べてみるのはどうでしょうか**

**Comment by risako1110** [comment]
いいと思います

**Comment by anon622** [comment]
### 逆に上からディバースですか
`いいですね`

**Comment by anon622** [comment]
> じゃぁ、夏に海に行きましょう

**Comment by risako1110** [comment]
サウナで汗いっぱい流しましょ

**Comment by anon622** [comment]
[サウナいいですね](url)

**Comment by risako1110** [comment]
宮崎行きたいです

**Comment by anon622** [comment]
@risako1110 いいですね。ぜひきてください

**Comment by risako1110** [comment]
yatta-!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by risako1110** [comment]
うれしいぜ！！！！！！！！！

**Comment by anon622** [comment]
よって愛音がやせるためには

- 海に行く

- サウナに行く

- 宮崎に行く

- お菓子を控える

- よく噛む

ということで決定します
